name: WhitelistGuiNK
main: com.deadlylegend.whitelistgui.Main
version: "1.0.0"
api: ["1.0.0", "1.0.11"]
author: DeadlyLegend
depend:
  - FormAPI
commands:
  whitelistgui:
    description: Opens the Whitelistgui
    usage: "/whitelistgui"
    aliases: ["wlg"]
    permission: whitelistgui.use
permissions:
    whitelistgui.use:
      description: "Allows you to use the WhitelistGUI"
      default: op

